### ISSUE TITLE
Can't install ldt

### ISSUE THREAD

**Issue by download13** [freenet/locutus#620] opened 2023-05-07 17:40 UTC
I was trying to mess around with locutus and used `cargo install locutus` like the guide said, but got this error near the end of the build process:

```
   Compiling locutus-core v0.0.3
error[E0432]: unresolved import `locutus_stdlib::api`
 --> C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\client_events.rs:3:21
  |
3 | use locutus_stdlib::api::ClientRequest;
  |                     ^^^ could not find `api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::api`
 --> C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\client_events.rs:4:21
  |
4 | use locutus_stdlib::api::{ClientError, HostResponse};
  |                     ^^^ could not find `api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::api`
  --> C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\client_events\combinator.rs:10:21
   |
10 | use locutus_stdlib::api::{ErrorKind, HostResponse};
   |                     ^^^ could not find `api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::api`
  --> C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\client_events\websocket.rs:11:21
   |
11 | use locutus_stdlib::api::{ClientRequest, ContractRequest, ErrorKind, HostResponse};
   |                     ^^^ could not find `api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::api`
  --> C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\contract\handler.rs:10:21
   |
10 | use locutus_stdlib::api::{ClientRequest, HostResponse};
   |                     ^^^ could not find `api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::api`
   --> C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\contract\handler.rs:196:25
    |
196 |     use locutus_stdlib::api::{ContractRequest, ContractResponse};
    |                         ^^^ could not find `api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::api`
 --> C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\contract\test.rs:7:21
  |
7 | use locutus_stdlib::api::{ClientRequest, HostResponse};
  |                     ^^^ could not find `api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::api`
 --> C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\executor.rs:7:21
  |
7 | use locutus_stdlib::api::{
  |                     ^^^ could not find `api` in `locutus_stdlib`

error[E0432]: unresolved imports `locutus_stdlib::api`, `super::ClientError`, `super::ClientError`
  --> C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\client_events\combinator.rs:13:26
   |
13 | use super::{BoxedClient, ClientError, HostResult};
   |                          ^^^^^^^^^^^
   |
  ::: C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\node.rs:18:21
   |
18 | use locutus_stdlib::api::{ClientRequest, ContractRequest};
   |                     ^^^ could not find `api` in `locutus_stdlib`
   |
  ::: C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\client_events\websocket.rs:15:13
   |
15 | use super::{ClientError, ClientEventsProxy, ClientId, HostResult, OpenRequest};
   |             ^^^^^^^^^^^

error[E0581]: return type references an anonymous lifetime, which is not constrained by the fn input types
   --> C:\Users\downl\.cargo\registry\src\github.com-1ecc6299db9ec823\locutus-core-0.0.3\src\executor.rs:138:10
    |
138 |     ) -> Response {
    |          ^^^^^^^^
    |
    = note: lifetimes appearing in an associated or opaque type are not considered constrained
    = note: consider introducing a named lifetime parameter

Some errors have detailed explanations: E0432, E0581.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `locutus-core` due to 10 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `locutus v0.0.3`, intermediate artifacts can be found at `C:\Users\downl\AppData\Local\Temp\cargo-installRwmxIs`
```

Should that be referring to `locutus_stdlib::client_api`? It looks like it is in the repository, but that doesn't seem to be the code that's in cargo.

**Comment by netsirius** [comment] 2023-05-08 21:55
Thank you for providing the error message you encountered. To better understand the problem and provide accurate guidance, I'd like to ask you about the steps you've taken to reproduce the issue.

The structure within locutus_stdlib has changed since version 0.0.3, which was uploaded to the crates registry. If the error persists while we investigate what might be happening, you can try installing the updated Locutus dev tools from the source code by running:

`cargo install --path crates/locutus-node`

**Comment by download13** [comment] 2023-05-10 05:50
```
error[E0432]: unresolved import `locutus_stdlib::client_api`
 --> crates\locutus-core\src\client_events.rs:3:21
  |
3 | use locutus_stdlib::client_api::ClientRequest;
  |                     ^^^^^^^^^^ could not find `client_api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::client_api`
 --> crates\locutus-core\src\client_events.rs:4:21
  |
4 | use locutus_stdlib::client_api::{ClientError, HostResponse};
  |                     ^^^^^^^^^^ could not find `client_api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::client_api`
  --> crates\locutus-core\src\client_events\combinator.rs:10:21
   |
10 | use locutus_stdlib::client_api::{ErrorKind, HostResponse};
   |                     ^^^^^^^^^^ could not find `client_api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::client_api`
  --> crates\locutus-core\src\client_events\websocket.rs:16:21
   |
16 | use locutus_stdlib::client_api::{ClientRequest, ContractRequest, ErrorKind, HostResponse};
   |                     ^^^^^^^^^^ could not find `client_api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::client_api`
  --> crates\locutus-core\src\contract\handler.rs:10:21
   |
10 | use locutus_stdlib::client_api::{ClientRequest, HostResponse};
   |                     ^^^^^^^^^^ could not find `client_api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::client_api`
  --> crates\locutus-core\src\contract\storages\rocks_db.rs:10:21
   |
10 | use locutus_stdlib::client_api::{ClientRequest, ContractRequest, ContractResponse, HostResponse};
   |                     ^^^^^^^^^^ could not find `client_api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::client_api`
 --> crates\locutus-core\src\contract\test.rs:7:21
  |
7 | use locutus_stdlib::client_api::{ClientRequest, HostResponse};
  |                     ^^^^^^^^^^ could not find `client_api` in `locutus_stdlib`

error[E0432]: unresolved import `locutus_stdlib::client_api`
 --> crates\locutus-core\src\executor.rs:7:21
  |
7 | use locutus_stdlib::client_api::{
  |                     ^^^^^^^^^^ could not find `client_api` in `locutus_stdlib`

error[E0432]: unresolved imports `locutus_stdlib::client_api`, `super::ClientError`, `super::ClientError`
  --> crates\locutus-core\src\client_events\combinator.rs:13:26
   |
13 | use super::{BoxedClient, ClientError, HostResult};
   |                          ^^^^^^^^^^^
   |
  ::: crates\locutus-core\src\node.rs:18:21
   |
18 | use locutus_stdlib::client_api::{ClientRequest, ContractRequest};
   |                     ^^^^^^^^^^ could not find `client_api` in `locutus_stdlib`
   |
  ::: crates\locutus-core\src\client_events\websocket.rs:19:13
   |
19 | use super::{ClientError, ClientEventsProxy, ClientId, HostResult, OpenRequest};
   |             ^^^^^^^^^^^
```

I think the problem might be that there are only implementations for the `client_api` module for "unix" and "wasm" targets. I'm on windows and can't seem to install `wasm32-unknown-unknown`.

**Comment by iduartgomez** [comment] 2023-05-10 07:39
Yeah, that's a problem... we need to fix that for windows.

**Comment by download13** [comment] 2023-05-11 00:58
Is there any reason the `client_api::regular` module can't be enabled for windows targets? I'm new to rust, but I didn't see any libraries in there that looked posix-dependent.

**Comment by iduartgomez** [comment] 2023-05-11 03:57
probably not, if you wanna try add windows as a feature flag and doing the installation locally and open a PR to fix this that would be welcome, don't have a windows machine set right now to try it out myself.

**Comment by iduartgomez** [comment] 2023-05-31 13:54
Merged the PR, if you can verify if it works now will close the issue.

**Closed** 2023-05-31 21:03 UTC
